spring:
  datasource:
    url: jdbc:h2:mem:quiz-app-db
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    hikari:
      pool-name: HikariCP
      maximum-pool-size: 10
      minimum-idle: 15
      idle-timeout: 30000
      connection-timeout: 20000
      max-lifetime: 1800000
      connection-test-query: SELECT 1
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 50
          fetch_size: 50
    open-in-view: false
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml

# Logging configuration for better SQL visibility
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Server settings for better performance in a dev environment
server:
  port: 8080
  servlet:
    context-path: /
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 2048

# Security settings for H2 console access
security:
  basic:
    enabled: false
  ignored: /h2-console/**

# Management and monitoring settings
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
